version: "3.3"
services:
  reverse-proxy:
   image: traefik:v2.0
   command:
     - "--api.insecure=true"
     - "--providers.docker"
     - "--providers.docker.swarmMode=true"
     - "--providers.docker.watch=true"
     - "--providers.docker.exposedByDefault=false"
     - "--providers.docker.endpoint=unix:///var/run/docker.sock"
     - "--providers.docker.network=traefik-public"
     - "--entryPoints.web.address=:80"
   ports:
     - "80:80"
     - "8080:8080"
   networks:
     - traefik-public
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   deploy:
     placement:
       constraints: [node.role == manager]
  
  lofo:
   image: victor2616/lofocats:latest
   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
   volumes:
     - .:/lofocats_ui
   ports:
     - "81:80"
   networks:
     - traefik-public
   deploy:
     replicas: 2
     restart_policy:
         condition: on-failure
     labels:
         - traefik.enable=true
         - traefik.http.routers.lofo.rule=Host(`34.125.255.57`) && Path(`/web`)
         - traefik.http.routers.lofo.entryPoints=web
         - traefik.http.routers.lofo.service=lofo-service
         - traefik.http.services.lofo-service.loadbalancer.server.port=80
         - traefik.docker.network=traefik-public


networks:
    traefik-public:
       external: true
