development:
  url: 'https://lofotcats.herokuapp.com'
  version: '1'

test:
  url: 'https://lofotcats.herokuapp.com'
  version: '1'

production:
  url: 'https://lofotcats.herokuapp.com/'
  version: '1'
